name: Create Release

on:
  push:
    branches:
      - develop

jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.17.x]
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GRAYCORE_GITHUB_TOKEN }}
          command: manifest
          default-branch: develop

      - uses: actions/checkout@v4
        with:
          ref: release-please--branches--develop--components--daffodil
          token: ${{ secrets.GRAYCORE_GITHUB_TOKEN }}

      - uses: graycoreio/github-actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          use-stamp-cache: true

      - name: Add Packages to README
        run: |
          git config user.name "GrayBot"
          git config user.email "automation@graycore.io"
          cd tools/release
          npx gulp addPackagesToReadme
          git add ../../README.md
          git commit -m 'docs: autogenerate package table in README' || true
          git push
